application: isolateserver-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /restricted/.*
  script: main.app
  secure: always
  login: admin

- url: /
  script: main.app
  secure: always
  login: required

- url: .*
  script: main.app
  secure: always

inbound_services:
- warmup
