application: chrome-infra-auth-dev
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Auth service is extending components/auth in non-trivial way.
# It's more manageable to list all auth components routes here instead of
# including them via separate WSGI app (like components/auth/include.yaml does).
- url: /auth/static/(.+)\.(css|gif|ico|js|ttf|svg)
  static_files: components/auth/ui/static/\1.\2
  upload: components/auth/ui/static/(.+)\.(css|gif|ico|js|ttf|svg)
  secure: always

- url: /auth_service/static/(.+)\.(css|gif|ico|js|ttf|svg)
  static_files: frontend/static/\1.\2
  upload: frontend/static/(.+)\.(css|gif|ico|js|ttf|svg)
  secure: always

- url: /.*
  script: frontend.main.app
  secure: always

builtins:
- appstats: on
- remote_api: on

includes:
- components/static_third_party.yaml

inbound_services:
- warmup

# https://developers.google.com/appengine/docs/python/tools/libraries27
# As the doc says, serious applications should specify the third party versions.
libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"
- name: yaml
  version: "3.10"

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^tests.*
- ^tools.*
- ^(.*/)?.*\.orig
- ^(.*/)?.*\.rej
- ^[A-Z]+
- ^[A-Z]+\.[a-z]+
