application: isolateserver-dev
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  min_idle_instances: 2
  min_pending_latency: 50ms
  max_pending_latency: 250ms

handlers:
- url: /internal/mapreduce(/.*)?
  script: map_reduce_jobs.app
  secure: always
  login: admin

- url: /internal.*
  script: main.app
  secure: always
  login: admin

- url: /restricted.*
  script: main.app
  secure: always
  login: admin

- url: /mapreduce/pipeline/images
  static_dir: third_party/mapreduce/lib/pipeline/ui/images
  secure: always

- url: /(.+)\.(css|gif|ico|js)
  static_files: static/\1.\2
  upload: static/(.+)\.(css|gif|ico|js)
  secure: always

- url: /.*
  script: main.app
  secure: always

builtins:
- appstats: on
- remote_api: on

inbound_services:
- warmup

# https://developers.google.com/appengine/docs/python/tools/libraries27
# As the doc says, serious applications should specify the third party versions.
libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"
- name: yaml
  version: "3.10"
- name: pycrypto
  version: "2.6"

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^tests.*
- ^tools.*
- ^(.*/)?.*\.orig
- ^(.*/)?.*\.rej
- ^[A-Z]+
- ^[A-Z]+\.[a-z]+
