application: swarmingserver
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

instance_class: F4
automatic_scaling:
  min_idle_instances: 2
  min_pending_latency: 50ms
  max_pending_latency: 250ms

handlers:
- url: /_ah/spi/.*
  script: main.endpoints_app
  secure: always

- url: /internal/mapreduce(/.*)?
  script: main.mapreduce_app
  secure: always
  login: admin

- url: /restricted/mapreduce(/.*)?
  script: main.mapreduce_app
  secure: always
  login: admin

- url: /mapreduce/pipeline/images
  static_dir: third_party/mapreduce/lib/pipeline/ui/images
  secure: always
  http_headers:
    Content-Security-Policy: "default-src https: 'self'"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options: deny

- url: /([^/]+)\.(css|ico|txt)
  static_files: static/\1.\2
  upload: static/(.+)\.(css|ico|txt)
  secure: always
  http_headers:
    Content-Security-Policy: "default-src https: 'self'"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options: deny

- url: /ui/polymer05/([^/]+\-build)\.(html|js)
  static_files: ui/polymer05/\1.\2
  upload: ui/polymer05/([^/]+\-build)\.(html|js)
  secure: always
  http_headers:
    # TODO(maruel): Unsure about polymer if it is inline-style free.
    # TODO(maruel): Polymer abuses eval() and http://crbug.com/277857 gets in
    # the way.
    Content-Security-Policy: "default-src https: 'self' 'unsafe-inline' 'unsafe-eval'"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options: deny

- url: /api/.*
  script: main.app
  secure: always

- url: /(user|restricted)(|/.*)
  script: main.app
  secure: always
  login: required

# TODO(maruel): Move /internal/ to module-backend.yaml.
- url: /internal/.+
  script: main.app
  secure: always
  login: admin

- url: /res/(.+)
  static_files: ui/build/\1
  upload: ui/build/(.+)
  secure: always
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options: deny

- url: .*
  script: main.app
  secure: always

builtins:
- deferred: on
- remote_api: on

inbound_services:
- mail
- warmup

includes:
- components/auth
- components/config
- components/ereporter2
- components/static_third_party.yaml
- gae_ts_mon

libraries:
- name: endpoints
  version: "1.0"
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"
- name: yaml
  version: "3.10"

skip_files:
# Test and tools.
- support/
- ^tests/
- ^tools/
- test_.+
- .+_test\.py$
# Junk files.
- ^(.*/)?\..*
- .+\.orig$
- .+\.rej$
- .+\.zip$
- ^(.*/)?#.*#
- .+~
- .+\.py[co]
# Doc, readme and license.
- ^doc/
- ^[A-Z]+$
- ^[A-Z]+\.[a-z]+$
- ui/node_modules/
- ui/res/imp/bower_components/