# Do not change. Use gae.py to upload a differently named instance.
application: your-machine-provider-id
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /_ah/spi/.*
  script: main.endpoints_app
  secure: always
- url: /internal/.*
  login: admin
  script: main.backend_app
  secure: always

includes:
- components/auth

libraries:
- name: endpoints
  version: 1.0
- name: jinja2
  version: 2.6
- name: pycrypto
  version: 2.6
- name: webob
  version: 1.2.3
- name: webapp2
  version: 2.5.2

skip_files:
# Test and tools.
- support/
- ^tests/
- ^tools/
- test_.+
- .+_test\.py$
# Junk files.
- ^(.*/)?\..*
- .+\.orig$
- .+\.rej$
- ^(.*/)?#.*#
- .+~
- .+\.py[co]
- ^[A-Z]+$
- ^[A-Z]+\.[a-z]+$
